product_development/urls.py
"""product_development URL Configuration
"""


from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from users.views import *

from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('funolympics/', include('videos_app.urls')),
    path('funolympics/', include('gallery_app.urls')),

    path('verification/', include('verify_email.urls')),
    # password reset implementations
    path('reset_password/', auth_views.PasswordResetView.as_view(
        template_name="reset_password.html"), name="reset_password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="reset_password_sent.html"),
         name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="reset.html"),
         name="password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="reset_password_complete.html"),
         name="password_reset_complete"),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from . import views

urlpatterns=[
    # user app
    path('login', views.login_view, name='login'),
    path('register', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('logout/', views.logout_view, name='logout'),
    path('my_profile/', views.profile_view, name='myprofile'),
    path('edit_profile/', views.edit_profile, name='editprofile'),
    
    # send message
    path('inbox/', views.inbox, name='inbox'),
    path('view-message/<str:pk>/', views.viewMessage, name='viewMessage'),
    path('create-message/<str:pk>/', views.create_message, name='create-message'),
    # create-message/<str:pk>/ --> id of the account to which the message is being sent
    
    # delete message
    path('delete-inbox/<str:pk>/', views.delete_reset_inbox, name="delete-inbox"),

    
    # view and respond to contact messages
    path('contact/', views.contact, name='contact'),
    path('contact-inbox/', views.contact_inbox, name='contact-inbox'),
    path('view-contact-mail/<str:pk>',views.viewContactMail, name='view-contact-mail'),
    
    # change password
    path('change-password/', views.change_password, name='change-password'),
    
    # deactivate and delete account
    path('deactivate/<str:pk>/', views.deactivate_account, name='deactivate-account') ,  
    path('delete/', views.delete_account, name='delete-account'),

]

videos_app/urls.py
from django.urls import path
from . import views

urlpatterns=[
   # app 
   path('',views.landing_page, name='landing_page'),
   path('home/', views.home, name="home"),
   path('admin-panel/', views.admin_panel, name="admin_panel"),
   
   # video 
   path('add-videos/', views.add_videos, name="add_videos"),
   path('video-description/<str:pk>/', views.video_desc, name="video_desc"),
   path('update-videos/<str:pk>/', views.update_videos, name="update_videos"),
   path('delete-videos/<str:pk>/', views.delete_videos, name="delete_videos"),
   path('all-videos/', views.all_videos, name="all_videos"),
   path('live-games/', views.live_games, name="live_games"),
   path('live-description/<str:pk>/', views.live_desc, name='live_desc'),
   path('add-live/',views.add_live, name='add_live'),
   # like highlight and live videos
   path('like/<str:pk>/', views.like, name="like_video"),
   path('like-live/<str:pk>/', views.like_live, name="like_live"),
   
   path('add-country/', views.add_country, name='add_country'),
   path('add-category/', views.add_category, name='add_category'),
   
   # fixtures and results
   path('fixtures/', views.fixtures, name='fixtures'),
   path('results/', views.results, name='results'),
   
   # news
   path('all-news/', views.all_news, name='all_news'),
   path('news-description/<str:pk>/', views.news_desc, name="news_desc"),
   path('add-news/',views.add_news, name='add_news'),
   
   # add misc
   path('add-fixtures/', views.add_fixtures, name='add_fixtures'),
   path('add-players/', views.add_players, name='add_players'),
   path('add-standings/', views.add_standing, name='add_standings'),
   
   # 
   
]
 

videos_app/models.py
from pickle import FALSE
from unicodedata import category
from django.db import models
from users.models import User
from users.models import Profile
import uuid
import datetime
from django_countries.fields import CountryField
from embed_video.fields import EmbedVideoField

from django.conf import settings

# Create your models here.


class Video (models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    video = models.FileField(upload_to="videos/", null=True)
    upload_by = models.ForeignKey(
        Profile, null=True, blank=True, on_delete=models.SET_NULL)
    category = models.ManyToManyField(
        'Category', blank=False, verbose_name="Sports Category")
    country = models.ManyToManyField(
        'Country', blank=False, verbose_name="Participating Countries")
    likes = models.ManyToManyField(
        User, blank=True, related_name='video_posts')
    video_views = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='video_views', blank=True, default="admin@gmail.com")
    uploaded = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):
        return self.title


class LiveVideo(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    url = EmbedVideoField(verbose_name="Live URL")
    upload_by = models.ForeignKey(
        Profile, null=True, blank=True, on_delete=models.SET_NULL)
    category = models.ManyToManyField(
        'Category', blank=True, verbose_name="Sports Category")
    country = models.ManyToManyField(
        'Country', blank=True, verbose_name="Participating Countries")
    venue = models.CharField(max_length=255, blank=True,
                             null=True, default="Bayjing FunOlympics Park")
    likes = models.ManyToManyField(
        settings.AUTH_USER_MODEL, blank=True, related_name='like_live')
    video_views = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='like_views', blank=True, default="admin@gmail.com")
    uploaded = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):
        return self.title


class Review(models.Model):
    comment_by = models.ForeignKey(
        Profile, on_delete=models.CASCADE, null=True)
    video = models.ForeignKey(Video, on_delete=models.CASCADE)
    comment = models.TextField(null=True, blank=False)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):
        return self.comment
    
    class Meta:
        ordering = ['-created']


class LiveComments(models.Model):
    comment_by = models.ForeignKey(
        Profile, on_delete=models.CASCADE, null=True)
    video = models.ForeignKey(LiveVideo, on_delete=models.CASCADE)
    comment = models.TextField(null=True, blank=False)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):
        return self.comment
    
    class Meta:
        ordering = ['-created']


class Category (models.Model):
    name = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):
        return self.name


class Country (models.Model):
    country = CountryField(blank=False, null=False,
                           verbose_name="Participating Country", blank_label="Select Country")
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):
        return str(self.country)



class News (models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=False)
    image = models.ImageField(null=True, blank=False, upload_to='images/news/')
    imageBy = models.CharField(max_length=200, default="Funolympics Admin")
    author = models.CharField(
        max_length=200, default="Funolympics Admin", null=True, blank=True)
    photo_caption = models.CharField(max_length=255, null=True, blank=True)
    category = models.ManyToManyField(
        'Category', blank=True, verbose_name="News Category")
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):
        return self.title
    


class Fixture (models.Model):
    fixture = models.CharField(max_length=200)
    date = models.DateField(verbose_name='Game Date')
    thumbnail = models.ImageField(
        upload_to='images/fixtures/', default='media/images/background/bg.png', blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):
        return self.fixture


class Standing (models.Model):
    country = models.CharField(max_length=200, unique=True)
    gold = models.IntegerField()
    silver = models.IntegerField()
    bronze = models.IntegerField()
    total = models.IntegerField()

    def __str__(self):
        return self.country


class Player(models.Model):
    name = models.CharField(max_length=255, unique=True)
    image = models.ImageField(
        null=True, blank=True, upload_to='images/players/', default='images/profile_pics/default.jpg')
    gold = models.IntegerField()
    silver = models.IntegerField()
    bronze = models.IntegerField()
    total = models.IntegerField()

    def __str__(self):
        return self.name

videos_app/forms.py
from dataclasses import fields
from fileinput import FileInput
from django_countries.fields import CountryField
from django.forms import ModelForm
from django import forms
from .models import Category, Country, Fixture, LiveVideo, Player, Video, Review, News, Standing, LiveComments


class VideoForm(ModelForm):
    class Meta:
        model = Video
        fields = ['title', 'description', 'video', 'category', 'country']
        widgets = {
            'description': forms.Textarea(attrs={'class': 'description-input'}),
            # 'video': forms.FileInput(attrs={'class': 'file-input'}),
            'Category': forms.SelectMultiple(attrs={'class': 'tag-input'}),
        }
        # fields = '__all__'


class LiveVideoForm(ModelForm):
    class Meta:
        model = LiveVideo
        fields = ['title', 'description', 'url',
                  'category', 'country', 'venue']
        widgets = {
            'url': forms.Textarea(attrs={'class': 'description-input'}),
            'description': forms.Textarea(attrs={'class': 'description-input'}),
            'category': forms.SelectMultiple(attrs={'class': 'tag-input'}),
        }


class ReviewForm (ModelForm):
    class Meta:
        model = Review
        fields = ['comment']
        widgets = {
            'comment': forms.Textarea(attrs={'class': 'comment-input', 'placeholder': 'Add a comment'}),
        }


class LiveCommentsForm(ModelForm):
    class Meta:
        model = LiveComments
        fields = ['comment']
        widgets = {
            'comment': forms.Textarea(attrs={'class': 'comment-input', 'placeholder': 'Add a comment'}),
        }


class CountryForm(ModelForm):
    class Meta:
        model = Country
        fields = ['country']


class CategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = ['name']


class NewsForm (ModelForm):
    class Meta:
        model = News
        fields = ['title', 'description', 'image',
                  'photo_caption', 'author', 'imageBy']
        widgets = {
            'description': forms.Textarea(attrs={'class': 'description-input'}),
        }


class FixtureForm(ModelForm):
    date = forms.DateField(
        widget=forms.widgets.DateInput(attrs={'type': 'date'}))

    class Meta:
        model = Fixture
        fields = ['fixture', 'date', 'thumbnail']


class PlayerForm(ModelForm):
    class Meta:
        model = Player
        fields = ['name', 'image', 'gold', 'silver', 'bronze', 'total']


class StandingForm(ModelForm):
    class Meta:
        model = Standing
        fields = ['country', 'gold', 'silver', 'bronze', 'total']

videos_app/templates/videos_app/add_misc.html
{% extends 'main.html' %}


{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'styles/add_videos.css' %}">
{% endblock styles %}



{% block content %}
<div class="container">

    {% if page == "add_fixtures" %}
    <div class="tab-buttons">
        <a href="{% url 'add_fixtures' %}" class="active-tab">Add Fixtures</a>
        <a href="{% url 'add_players' %}">Add Players</a>
        <a href="{% url 'add_standings' %}">Add Latest Standing</a>
    </div>

    <form id="default-form" method="POST" novalidate enctype="multipart/form-data">
        <h2>Add a new fixture</h2>
        {% csrf_token %}
        {% for field in fixtureform %}
        <div class="input-errors">
            {{field.label_tag}}
            <div class="input-fields">
                {{field}}
            </div>

            <div class="errors-div">
                {% for error in field.errors %}
                <small style="color: red">{{error}}</small>
                {% endfor %}
            </div>
        </div>
        {% endfor %}
        <input type="submit" value="Add Fixture" class="default-button--large" />
    </form>


    <!-- ==================================================================== -->
    <!-- Add Players -->
    {% elif page == "add_players" %}
    <div class="tab-buttons">
        <a href="{% url 'add_fixtures' %}">Add Fixtures</a>
        <a href="{% url 'add_players' %}" class="active-tab">Add Players</a>
        <a href="{% url 'add_standings' %}">Add Latest Standing</a>
    </div>

    <form id="default-form" method="POST" novalidate enctype="multipart/form-data">
        <h2>Add a new player</h2>

        {% csrf_token %}
        {% for field in playerform %}
        <div class="input-errors">
            {{field.label_tag}}
            <div class="input-fields">
                {{field}}
            </div>

            <div class="errors-div">
                {% for error in field.errors %}
                <small style="color: red">{{error}}</small>
                {% endfor %}
            </div>
        </div>
        {% endfor %}
        <input type="submit" value="Add Player" class="default-button--large" />
    </form>
    <!-- ====================================================== -->
    {% else %}
    <div class="tab-buttons">
        <a href="{% url 'add_fixtures' %}">Add Fixtures</a>
        <a href="{% url 'add_players' %}" >Add Players</a>
        <a href="{% url 'add_standings' %}"class="active-tab">Add Latest Standing</a>
    </div>

    <form id="default-form" method="POST" novalidate enctype="multipart/form-data">
        <h2>Add standings</h2>

        {% csrf_token %}
        {% for field in standingform %}
        <div class="input-errors">
            {{field.label_tag}}
            <div class="input-fields">
                {{field}}
            </div>

            <div class="errors-div">
                {% for error in field.errors %}
                <small style="color: red">{{error}}</small>
                {% endfor %}
            </div>
        </div>
        {% endfor %}
        <input type="submit" value="Add Standing" class="default-button--large />
    </form>

    {% endif %}
</div>



{% endblock content %}

videos_app/templates/videos_app/add_news.html
{% extends 'main.html' %}


{% block title %}Add News - FunOlympics{% endblock title %}

{% load static %}

{% block styles %}
<link rel="stylesheet" href="{% static 'styles/add_videos.css' %}">
{% endblock styles %}



{% block content %}

<div class="container">
  <h3>Add news</h3>
  <form action="" method="POST" novalidate enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in newsform %}
    <div class="input-errors">
      {{field.label_tag}}
      <div class="input-fields">
        {{field}}
      </div>

      <div class="errors-div">
        {% for error in field.errors %}
        <small style="color: red">{{error}}</small>
        {% endfor %}
      </div>
    </div>
    {% endfor %}
    <input type="submit" value="Add News" class="default-button--large">
  </form>
</div>

{% endblock content %}

videos_app/templates/videos_app/add_videos.html
{% extends 'main.html'%}

{% block title %}Add Videos - FunOlympics{% endblock title %}

{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'styles/add_videos.css' %}">
{% endblock %}


{% block content%}

<!-- This template is used to generate forms to add new videos, live videos, sports category and participating countries -->

<div class="container">

  <!-- Add new live videos -->
  <!-- ============================================================= -->
  {% if page == 'add_live' %}

  <div class="tab-buttons">
    <a href="{% url 'add_live' %}" class="active-tab">Add Live Videos</a>
    <a href="{% url 'add_videos' %}">Add Videos</a>
    <a href="{% url 'add_country' %}">Add Participating Countries</a>
    <a href="{% url 'add_category' %}">Add Sports Category</a>
  </div>


  <form action="" id="default-form" method="POST" novalidate>

    <h2>Add a new live video</h2>

    {% csrf_token %}
    {% for field in liveform %}
    <div class="input-errors">
      {{field.label_tag}}
      <div class="input-fields">
        {{field}}
      </div>

      <div class="errors-div">
        {% for error in field.errors %}
        <small style="color: red">{{error}}</small>
        {% endfor %}
      </div>
    </div>
    {% endfor %}
    <input type="submit" value="Add Live Video" class="default-button--large" >
  </form>

  <!-- Add country -->
  <!-- ================================================================= -->


  {% elif page == 'add_country' %}
  <div class="tab-buttons">
    <a href="{% url 'add_live' %}">Add Live Videos</a>
    <a href="{% url 'add_videos' %}">Add Videos</a>
    <a href="{% url 'add_country' %}" class="active-tab">Add Participating Countries</a>
    <a href="{% url 'add_category' %}">Add Sports Category</a>
  </div>

  <form action="" id="default-form" method="POST" novalidate>

    <h2>Add a participating country</h2>

    {% csrf_token %}
    {% for field in countryform %}
    <div class="input-errors">
      {{field.label_tag}}
      <div class="input-fields">
        {{field}}
      </div>

      <div class="errors-div">
        {% for error in field.errors %}
        <small style="color: red">{{error}}</small>
        {% endfor %}
      </div>
    </div>
    {% endfor %}
    <input type="submit" value="Add Country" class="default-button--large" >
  </form>


  <!-- Add new sports category form -->
  <!-- ===============================================================  -->
  {% elif page == 'add_category' %}

  <div class="tab-buttons">
    <a href="{% url 'add_live' %}">Add Live Videos</a>
    <a href="{% url 'add_videos' %}">Add Videos</a>
    <a href="{% url 'add_country' %}">Add Participating Countries</a>
    <a href="{% url 'add_category' %}" class="active-tab">Add Sports Category</a>
  </div>

  <form action="" id="default-form" method="POST" novalidate>

    <h2>Add a sports category</h2>

    {% csrf_token %}
    {% for field in categoryform %}
    <div class="input-errors">
      {{field.label_tag}}
      <div class="input-fields">
        {{field}}
      </div>

      <div class="errors-div">
        {% for error in field.errors %}
        <small style="color: red">{{error}}</small>
        {% endfor %}
      </div>
    </div>
    {% endfor %}
    <input type="submit" value="Add Sports Category" class="default-button--large" >
  </form>

  <!-- Add new video form -->
  <!-- ===============================================================  -->
  {% else %}
  <div class="tab-buttons">
    <a href="{% url 'add_live' %}">Add Live Videos</a>
    <a href="{% url 'add_videos' %}" class="active-tab">Add Videos</a>
    <a href="{% url 'add_country' %}">Add Participating Countries</a>
    <a href="{% url 'add_category' %}">Add Sports Category</a>
  </div>

  <form id="default-form" method="POST" novalidate enctype="multipart/form-data">
    <h2>Add a new video</h2>
    {% csrf_token %}
    {% for field in form %}
    <div class="input-errors">
      {{field.label_tag}}
      <div class="input-fields">
        {{field}}
      </div>

      <div class="errors-div">
        {% for error in field.errors %}
        <small style="color: red">{{error}}</small>
        {% endfor %}
      </div>
    </div>
    {% endfor %}
    <input type="submit" value="Add Video" class="default-button--large" />
  </form>
  {% endif %}
</div>

{% endblock content %}

videos_app/templates/videos_app/all_news.html
{% extends 'main.html'%}


{% block title %}Latest News - FunOlympics{% endblock title %}

{% load static%}
{% block styles%}
<link rel="stylesheet" href="{% static 'styles/all_news.css' %}">
{% endblock styles %}


{% block content%}

<div class="container">

    <div class="news-container">
        <div class="header">
            <h2>Latest news</h2>
        </div>

        <div class="news-card-container">
            {% if search_query%}
            <p style="color:#3AB09E">Search results for {{search_query}}</p>
            {% endif %}
            {% for news in news %}
            <a href="{% url 'news_desc' news.id %}">
                <div class="news-card">
                    <div class="news-thumbnail">
                        <img src="{{news.image.url}}">
                    </div>
                    <div class="news-details">
                        <p>{{news.title}}</p>
                        <p>{{news.description}}</p>
                    </div>
                </div>

            </a>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock content %}
{% block footer %}
{% include 'footer.html' %}

{% endblock footer %}

videos_app/templates/videos_app/delete_confirmation.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delte confirmation</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'styles/uikit.css' %}">
</head>
<body>
    
</body>
</html>
<form action="" method="POST">
    {% csrf_token %}
    <p>Delete confirmation.</p>
    <a href="{% url 'home' %}">Cancel</a>
    <input type="submit" value="Confirm" class="default-button--sm">
    
</form>

videos_app/templates/videos_app/live_desc.html
{% extends 'main.html'%}

{% block title %}{{video.title}}{% endblock title %}

{% load static %}

{% block styles %}
<link rel="stylesheet" href="{% static 'styles/video_desc.css' %}">
{% endblock %}

{% block content %}
<div class="container">
    <div class="left-container">
        <div class="player">
            <iframe src="{{video.url}}" frameborder="0" style="width: 95%; height:480px"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </div>
        <div class="video-details">
            <div class="video-desc">
                <p> {{video.title}}</p>
                <div class="tags">
                    {% for category in video.category.all %}
                    <small>{{category}}</small>
                    {% endfor %}
                    {% for country in video.country.all %}
                    <small>{{country}}</small>
                    {% endfor %}
                </div>
                <div class="social-share">
                    {% include 'social_share.html' %}
                </div>


                <div class="views-buttons">
                    <p style="margin-right:20px ;">{{video_views}} views</p>
                    <p>{{video.uploaded}}</p>
                    <div class="like-buttons">
                        <!-- Like form -->
                        <form action="{% url 'like_live' video.id %}" method="POST">
                            {% csrf_token %}
                            {% if liked %}
                            <button type="submit" name="video_id" value="{{video.id}}" class="btn-small">
                                <i class="fa-solid fa-thumbs-up" style="color: #3AB09E;"></i></button>
                            {% else %}
                            <button type="submit" name="video_id" value="{{video.id}}" class="btn-small">
                                <i class="fa-solid fa-thumbs-up"></i></button>
                            {% endif %}
                            <p>{{total_likes}} likes</p>
                        </form>
                    </div>
                </div>
            </div>
            <p>{{video.description}}</p>
        </div>


        <div class="comments-section">

            <h3>{{total_comments}} Comments</h3><br>
            <form action="{% url 'live_desc' video.id %}" method="post">
                {% csrf_token %}
                {% for field in form %}
                <div class="input-fields">
                    {{field}}
                </div>
                {% endfor %}
                <input type="submit" value="Comment" id="comment-button">
            </form>

            {% for comment in video.livecomments_set.all %}
            <div class="comment-container">
                <img src="{{comment.comment_by.profile_image.url}}" style="width:30px; height:30px; border-radius:50%"
                    alt="">
                <div class="user-comment">
                    <p>{{comment.comment_by.username}}</p>
                    <p>{{comment.comment | linebreaksbr}}</p>
                </div>
                <p id="date">{{comment.created}}</p>
            </div>
            {% endfor %}
        </div>
    </div>

    <div class="right-container">
        <h3>Recommendations</h3>
        {% for video in videos %}
        <div class="video-card">
            <a href="{% url 'live_desc' video.id %}" style="text-decoration: none; width:100%;">
                <div class="thumbnail">
                    <iframe src="{{video.url}}" frameborder="0" autoplay allowfullscreen
                        style="width: 200px; height: 100px;"></iframe>
                </div>
                <div class="card-details">
                    <p><a href="{% url 'live_desc' video.id %}">{{video.title}}</a></p>
                </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}

{% block footer %}
{% include 'footer.html' %}
{% endblock footer %}

videos_app/templates/videos_app/video_desc.html
{% extends 'main.html'%}

{% block title %}{{video.title}}{% endblock title %}

{% load static %}

{% block styles %}
<link rel="stylesheet" href="{% static 'styles/video_desc.css' %}">
{% endblock %}

{% block content %}
<div class="container">
    <div class="left-container">
        <div class="player">
            <video src="{{video.video.url}}" type="video/mp4" controls style="width: 95%;" preload="auto" loop
                autoplay></video>
        </div>
        <div class="video-details">
            <div class="video-desc">
                <p>{{video.title}}</p>
                <div class="tags">
                    {% for category in video.category.all %}
                    <small>{{category}}</small>
                    {% endfor %}
                    {% for country in video.country.all %}
                    <small>{{country}}</small>
                    {% endfor %}
                </div>
                <div class="social-share">
                    {% include 'social_share.html' %}
                </div>


                <div class="views-buttons">
                    <p style="margin-right:20px ;">{{video_views}} views</p>
                    <p>{{video.uploaded}}</p>
                    <div class="like-buttons">
                        <!-- Like form -->
                        <form action="{% url 'like_video' video.id %}" method="POST">
                            {% csrf_token %}
                            {% if liked %}
                            <button type="submit" name="video_id" value="{{video.id}}" class="btn-small">
                                <i class="fa-solid fa-thumbs-up" style="color: #3AB09E;"></i></button>
                            {% else %}
                            <button type="submit" name="video_id" value="{{video.id}}" class="btn-small">
                                <i class="fa-solid fa-thumbs-up"></i></button>
                            {% endif %}
                            <p>{{total_likes}} likes</p>
                        </form>
                    </div>
                </div>
            </div>
            <p>{{video.description}}</p>
        </div>


        <div class="comments-section">

            <h3>{{total_comments}} Comments</h3><br>
            <form action="{% url 'video_desc' video.id %}" method="post">
                {% csrf_token %}
                {% for field in form %}
                <div class="input-fields">
                    {{field}}
                </div>
                {% endfor %}
                <input type="submit" value="Comment" id="comment-button">
            </form>
            
            {% for review in video.review_set.all %}
            <div class="comment-container">
                <img src="{{review.comment_by.profile_image.url}}" style="width:30px; height:30px; border-radius:50%"
                    alt="">
                <div class="user-comment">
                    <p>{{review.comment_by.username}}</p>
                    <p>{{review.comment | linebreaksbr}}</p>
                </div>
                <p id="date">{{review.created}}</p>
            </div>
            {% endfor %}
        </div>
    </div>

    <div class="right-container">
        <h3>Recommendations</h3>
        {% for video in videos %}
        <div class="video-card">
            <a href="{% url 'video_desc' video.id %}" style="text-decoration: none; width:100%;">
                <div class="thumbnail">
                    <video src="{{video.video.url}}" type="video/mp4" style="width: 200px; height: 100px;"></video>
                </div>
                <div class="card-details">
                    <p><a href="{% url 'video_desc' video.id %}">{{video.title}}</a></p>
                </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}

{% block footer %}
{% include 'footer.html' %}
{% endblock footer %}